=== BGMitkov/xmk/dam.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema	xmlns:xs="http://www.w3.org/2001/XMLSchema"
						targetNamespace="http://www.w3schools.com/dam" 
						xmlns:tns="http://www.w3schools.com/dam"
						elementFormDefault="qualified">

	<xs:complexType name="DamCatalogType">
		<xs:sequence>
			<xs:element name="Dams" type="tns:DamsType"/>
			<xs:element name="Fauna" type="tns:FaunaType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DamsType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="Dam" type="tns:DamType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="DamType">
		<xs:sequence>
			<xs:element name="Wall" type="tns:WallType" minOccurs="0"/>
			<xs:element name="FaunaIds" type="tns:FaunaIdsType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="damId" type="xs:positiveInteger" use="required"/>		
		<xs:attribute name="location" type="xs:string"/>
		<xs:attribute name="nearestCity" type="xs:string"/>
		<xs:attribute name="source" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="length" type="xs:decimal" />
		<xs:attribute name="depth" type="xs:decimal" />
		<xs:attribute name="width" type="xs:decimal" />
		<xs:attribute name="seaLevel" type="xs:int" />
		<xs:attribute name="area" type="xs:decimal" />
		<xs:attribute name="waterVolume" type="xs:decimal" />
		<xs:attribute name="yearBuildStarted" type="xs:gYear" />
		<xs:attribute name="yearBuildFinished" type="xs:gYear" />
	</xs:complexType>
	
	<xs:complexType name="WallType">
		<xs:attribute name="height" type="xs:decimal"/>
		<xs:attribute name="length" type="xs:decimal"/>
		<xs:attribute name="groundBase" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="FaunaIdsType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="faunaId" type="xs:positiveInteger"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="FaunaType">
		<xs:sequence maxOccurs="unbounded" minOccurs="0">
			<xs:element name="Fauna">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string"/>
					<xs:attribute name="faunaId" type="xs:positiveInteger"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="DamCatalog" type="tns:DamCatalogType"/>
</xs:schema>

=== BGMitkov/xmk/dam.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XSLTFile.xslt"?>

<DamCatalog xmlns="http://www.w3schools.com/dam"
						xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						xsi:schemaLocation="http://www.w3schools.com/dam dam.xsd">
    <Dams>
			<Dam DamID="1" name="Al. Stamboliiski" seaLevel="190" area="11,4" waterVolume="205" WallID="1"/>
			<Dam DamID="2" name="Batak" seaLevel="1107" area="22" waterVolume="310" WallID="2"/>
			<Dam DamID="3" name="Belmeken" seaLevel="1923" area="4.5" waterVolume="144" WallID="3"/>
			<Dam DamID="4" name="Vucha" seaLevel="540" area="4.9" waterVolume="226" WallID="4"/>
			<Dam DamID="5" name="Golqm Beglik" seaLevel="1528" area="4.1" waterVolume="62" WallID="5"/>
			<Dam DamID="6" name="Gorni Dubnik" seaLevel="168" area="11" waterVolume="135" WallID="6"/>
			<Dam DamID="7" name="Dospat" seaLevel="1200" area="22" waterVolume="449" WallID="7"/>
			<Dam DamID="8" name="Jrebchevo" seaLevel="269" area="22.4" waterVolume="400" WallID="8"/>
			<Dam DamID="9" name="Ivailovgrad" seaLevel="120" area="15" waterVolume="188" WallID="9"/>
			<Dam DamID="10" name="Iskar" seaLevel="817" area="30" waterVolume="673" WallID="10"/>
			<Dam DamID="11" name="Jovkovtsi" seaLevel="365" area="25.6" waterVolume="92" WallID="11"/>
			<Dam DamID="12" name="Kamchia" seaLevel="260" area="9.6" waterVolume="233" WallID="12"/>
			<Dam DamID="13" name="Koprinka" seaLevel="400" area="11.2" waterVolume="140" WallID="13"/>
			<Dam DamID="14" name="Kurdjali" seaLevel="331" area="16" waterVolume="539" WallID="14"/>
			<Dam DamID="15" name="Ovcharitsa" seaLevel="140" area="6.3" waterVolume="45" WallID="15"/>
			<Dam DamID="16" name="Ogosta" seaLevel="186" area="23.6" waterVolume="506" WallID="16"/>
			<Dam DamID="17" name="Piasachnik" seaLevel="290" area="9.1" waterVolume="103" WallID="17"/>
			<Dam DamID="18" name="Studen kladenets" seaLevel="227" area="27.8" waterVolume="489" WallID="18"/>
			<Dam DamID="19" name="Ticha" seaLevel="185" area="18.7" waterVolume="311" WallID="19"/>
			<Dam DamID="20" name="Topolnitsa" seaLevel="370" area="5.7" waterVolume="137" WallID="20"/>
			<Dam DamID="21" name="Trakiets" seaLevel="250" area="8.2" waterVolume="114" WallID="21"/>
			<Dam DamID="22" name="Tsenkov kamak" seaLevel="668" area="3.4" waterVolume="111" WallID="22"/>
			<Dam DamID="23" name="Tsonevo" seaLevel="185" area="23.9" waterVolume="330" WallID="23"/>
			<Dam DamID="24" name="Shiroka poliana" seaLevel="1500" area="4" waterVolume="24" WallID="24"/>
	</Dams>
	<Walls>
    <Wall height="66" length="300" WallID="1"/> 
    <Wall height="35" length="237" WallID="2"/>
    <Wall height="24" length="210" WallID="3"/>
    <Wall height="144" length="420" WallID="4"/>
    <Wall height="46.5" length="191" WallID="5"/>
    <Wall height="35" length="180" WallID="6"/>
    <Wall height="60.5" length="230" WallID="7"/>
    <Wall height="50" length="60" WallID="8"/>
    <Wall height="71" length="250" WallID="9"/>
    <Wall height="76" length="204" WallID="10"/>
    <Wall height="66" length="256" WallID="11"/>
    <Wall height="25" length="165" WallID="12"/>
    <Wall height="44" length="315" WallID="13"/>
    <Wall height="103.5" length="403" WallID="14"/>
    <Wall height="22" length="1480" WallID="15"/>
    <Wall height="42" length="1000" WallID="16"/>
    <Wall height="37" length="271" WallID="17"/>
    <Wall height="67.5" length="338" WallID="18"/>
    <Wall height="55.5" length="635" WallID="19"/>
    <Wall height="78" length="232" WallID="20"/>
    <Wall height="67" length="321" WallID="21"/>
    <Wall height="130.5" length="468" WallID="22"/>
    <Wall height="39" length="890" WallID="23"/>
    <Wall height="35" length="139" WallID="24"/>
	</Walls>
</DamCatalog>
